### ISSUE TITLE
Add ability to specify lifetime for AutoMapper services

### ISSUE THREAD

**Issue by shatl** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#41]
Add ability to specify lifetime for AutoMapper services:
* `IValueResolver<,,>`,
* `IMemberValueResolver<,,,>`,
* `ITypeConverter<,>`, 
* `IMappingAction<,>`,
* `IMapper`

**Comment by jbogard** [comment]
Why?

**Comment by shatl** [comment]
In case all services does not have any transient or scoped dependencies, they can be registered as singletones to reduce memory traffic.

**Comment by jbogard** [comment]
If you register these explicitly after you call AddAutoMapper, does it not override that configuration?

**Comment by shatl** [comment]
@jbogard Yep, but I won't be able to reuse assembly scanning implemented in this library

**Comment by jbogard** [comment]
No you combine both, you first scan to get the 90% case then you register
the explicit exceptions to the case.

Unless you want to override for all the kinds of types but that seems easy
to get wrong.

**Comment by shatl** [comment]
Actually my case is opposite: most, if not all Automapper services are singletones :)

**Comment by jbogard** [comment]
I have to be very careful with that, because singletons can't have
dependencies on transients/scoped instances. Well, they can but it can
cause problems. So my defaults that I have are the "safe" defaults where
you can't mess anything up.

For a package that is really meant to be the "easy mode" to integrate, I'd
opt for the safe path. If you want more advanced registration, you're
better off just doing it yourself (and probably using a real container).

**Comment by sfmskywalker** [comment]
@jbogard I am not sure I understand, so please forgive me if I'm asking something silly. But what would be the issue of allowing an optional argument specifying the lifetime with which to register `IMapper` (and its dependencies? I agree that a good default is the `Scoped` lifetime, but it seems an omission to not allow for Singleton scope, which effectively disables singleton services from injecting IMapper.

to support that, we would basically have to copy your code and do it ourselves - but isn't the purpose of this package to not have to do that?

I'm probably overlooking something, but otherwise I hope you reconsider.

**Comment by jbogard** [comment]
So in your case, as a singleton, if you want transient dependencies, you'll
need to have a dependency on an IServiceScopeFactory, create a scope, and
resolve from there. I do this in integration tests for example, where I
only have the root service provider but I need things marked as "Scoped",
like a DbContext.

**Comment by sfmskywalker** [comment]
> IMapper really should never be Singleton anyway, since it
depends on a factory.

Now I see. Using a IServiceScopeFactory in a singleton makes sense. Thanks!

Speaking of DbContext, the extension method to register DbContext does allow for it to use a different lifetime, which is an optional argument similar to what's been done here: https://github.com/alphacloud/AutoMapper.Extensions.Microsoft.DependencyInjection/commit/e5534776e5732ff071fe6da2de167e0c6326bfdb
