### ISSUE TITLE
services.AddAutoMapper() breaks EF Core CLI

### ISSUE THREAD

**Issue by branhill** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#49]
When I run the `dotnet ef database drop` command, it throws exception:

```
An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: Mapper already initialized. You must call Initialize once per application domain/process.
Unable to create an object of type 'ApplicationDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<ApplicationDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.
```

It seems to caused by `services.AddAutoMapper()` in ASP.NET Core `ConfigureServices` method. When I comment this line, command works fine. I tried other commends like database update or migrations, this problem won't happen.

Solution from #36 works. But I think the default extension method shouldn't break EF Core CLI.

I'm using AutoMapper 6.2.2 and AutoMapper.Extensions.Microsoft.DependencyInjection 3.2.0, with Entity Framework Core 2.1.0-preview1-final.

**Comment by jbogard** [comment]
It’s not supposed to be called twice. You can call Mapper.Resetbefore to
allow it to be called twice.

**Comment by branhill** [comment]
Thanks for you reply. I wonder could it add to the extension method by default for better out-of-the-box, after all EF Core CLI is a really common tool.

**Comment by jbogard** [comment]
TBQH I'm surprised nothing else would break. Would make sense to do
Mapper.Reset inside of services.AddAutoMapper then?

**Comment by lbargaoanu** [comment]
@jbogard And then we're back to square one :)

**Comment by jbogard** [comment]
lol I know. Even worse, there are folks that do this in unit tests that run in parallel, and obviously `Mapper.Initialize` won't be thread-safe. The *safest* thing to do would be to turn off the static registration in this case. If you want it to be called twice, either use `Mapper.Reset` or instance-based.

@branhill the fundamental issue is that `services.AddAutoMapper` calls `Mapper.Initialize` which should only be called once. We turned off the ability to call it twice because it was a destructive operation, clearing out previous configuration. You can't add configuration on top either, you'd get weird order of calling issues.

We used to allow you to call `Initialize` multiple times, by calling `Reset` but then at runtime people would have issues with separate parts of their codebase calling `Initialize`, wiping things out.

I don't know if resetting is right, either, since it's a destructive operation. I don't know a good way around this other than making `services.AddAutoMapper` idempotent BUT ignoring previous configuration. That would require something like `Mapper.Configure` instead of `Mapper.Initialize`.

**Comment by branhill** [comment]
@jbogard  I did some search in EF Core repo, looks like they add a new argument to avoid this problem. 
aspnet/EntityFrameworkCore#10636

**Comment by jbogard** [comment]
So I don't think I want to check to see if it's been run before - what if
this is a different service collection?

Maybe the right thing to do is to reset first.

**Comment by micheleissa** [comment]
Adding the new argument still does not fix the issue. I have the latest nuget for aps.net core installed and still getting the same exact error. Any ideas @jbogard 
AutoMapper 6.2.2
AutoMapper.Extensions.Microsoft.DependencyInejection 3.2.0
AspNetCore.All 2.0.6
EFCore 2.0.2

**Comment by jbogard** [comment]
Call Mapper.Reset before AddAutoMapper.

**Comment by micheleissa** [comment]
But the doc for the function indicates that I should not do that for production!
What are the consequences of me doing that?

**Comment by jbogard** [comment]
It just resets the configuration. If you're using it in production it usually means you're doing something wrong. In the case of EF Core, I would say that *it* is doing something wrong. Calling `ConfigureServices` multiple times just seems like a bad idea in general.

You could also do a little check, a static field `IsAutoMapperInitialized` and do a check:

```c#
if (!IsAutoMapperInitialized) {
    services.AddAutoMapper();
    IsAutoMapperInitialized = true;
}
```

**Comment by RyanDennis2018** [comment]
In the Startup class, add:
**private readonly IHostingEnvironment _env;**

Inject Startup ctor with the IHostingEnv param:
public Startup(IConfiguration config, **IHostingEnvironment env**)
		{
			_config = config;
			**_env = env;**
		}

In Configure Services method, add condition to reset mapper if in Development:
 public void ConfigureServices(IServiceCollection services)
        {
**if (_env.IsDevelopment())
			{
				Mapper.Reset();
			}**
services.AddAutoMapper();
		
}

This is my solution and the assumption here is that the database will only be modified using EF tools if the hosting environment is set to Development.

**Comment by JohnGalt1717** [comment]
This really isn't a solution because you should be running your tests with your release code when doing devops. (i.e. the same code as is going into production)

I'm using services.AddAutoMapper(Assembly.GetAssembly(typeof(xxx)) to load everything. It would be nice of instead of it freaking out it just did an Except on the existing mappings and added any new ones.

**Comment by jbogard** [comment]
There's just not a great way around this right now, other than to ditch the static mapper:

```
AutoMapper.ServiceCollectionExtensions.UseStaticRegistration = false;
services.AddAutoMapper(typeof(Startup));
```

That's our default on our projects, anyway.

**Comment by JohnGalt1717** [comment]
@jbogard That doesn't work reliably either.

**Comment by jbogard** [comment]
Why? What are you seeing if you turn static registration off?

**Comment by jbogard** [comment]
"It"? Is that AutoMapper? EF Core? If you're using `ProjectTo` it's not going to work unless you're passing in the configuration, as the exception message indicates.

Honestly, I should just remove static registration from this library, it causes more trouble than it's worth.
